name: vuepress-theme-default-plus
services:
  node:
    type: node:14
    build:
      - yarn install
    scanner: false
    ssl: false
    sslExpose: false
    overrides:
      ports:
        - 8071:8071
tooling:
  node:
    service: node
  yarn:
    service: node
  dev:
    service: node
    cmd: yarn dev --port 8071
    env:
      DEBUG: "@lando/*"
