name: vitepress-theme-default-plus
services:
  node:
    type: node:18
    build:
      - npm install
    scanner: false
    ssl: false
    sslExpose: false
    overrides:
      ports:
        - 8071:8071
tooling:
  node:
    service: node
  npm:
    service: node
  dev:
    service: node
    cmd: npm run dev --port 8071
    env:
      DEBUG: "@lando/*"
