[build]
  base = "./"
  publish = "docs/.vuepress/dist"
  command = "yarn build"

# Sets our asset optimization
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

# Caches our images for 1 year
[[headers]]
  for = "/images/*"
  [headers.values]
	  Cache-Control = "public, max-age=31536000"

# This makes sure static assets are handled properly
# [[redirects]]
#   from = "/:version/:type/*"
#   to = "/:version/:type/:splat"
#   status = 200
#   force = true

# this sets 1.x as the "base" domain
[[redirects]]
  from = "/*"
  to = "/1.x/:splat"
  status = 200
  force = true

