[build]
  base = "./"
  publish = "docs/.vuepress/dist"
  command = "yarn build"

# Sets our asset optimization
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

# Caches our images for 1 year
[[headers]]
  for = "/images/*"
  [headers.values]
	  Cache-Control = "public, max-age=31536000"

[[redirects]]
  from = "/1.x/*"
  to = "/:splat"
  status = 200
