[build]
  base = "./"
  publish = "docs/.vitepress/dist/"
  command = "npm run build"

# Sets our asset optimization
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

# Caches our images for 1 year
[[headers]]
  for = "/images/*"
  [headers.values]
	  Cache-Control = "public, max-age=31536000"

# pluginz
# https://github.com/netlify/netlify-plugin-lighthouse#readme
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"

# https://github.com/munter/netlify-plugin-checklinks#readme
[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
    skipPatterns = [ ".rss", ".gif", ".jpg", 'x.com', 'twitter.com' ]
    checkExternal = true
