[build]
  base = "./"
  publish = "docs/.vitepress/dist/"
  command = "npx mvb docs"

[context.deploy-preview]
  command = "npm run build"
# https://github.com/munter/netlify-plugin-checklinks#readme
[[context.deploy-preview.plugins]]
  package = "netlify-plugin-checklinks"
  [context.deploy-preview.plugins.inputs]
    todoPatterns = [ "load", "CHANGELOG.html", "x.com", "twitter.com", "/v/" ]
    skipPatterns = [ ".rss", ".gif", ".jpg", "--vitepress-theme-default-plus.netlify.app" ]
    checkExternal = true

# Sets our asset optimization
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = false
[build.processing.images]
  compress = true

# Caches our images for 1 year
[[headers]]
  for = "/images/*"
  [headers.values]
	  Cache-Control = "public, max-age=31536000"

# https://github.com/netlify/netlify-plugin-lighthouse#readme
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
