export default {
  base: '/',
  lang: 'en-US',
  markdown: {},
  themeConfig: {
    alert: false,
    autometa: false,
    containers: {
      'brand': {defaultTitle: 'BRAND'},
      'box': {},
      'box-blue': {},
      'box-brand': {},
      'box-green': {},
      'box-red': {},
      'box-yellow': {},
      'caption': {},
      'card': {},
      'center': {},
      'half': {},
      'highlight': {},
      'left': {},
      'right': {},
      'success': {defaultTitle: 'SUCCESS'},
      'third': {},
      'thumbnail': {},
    },
    contributors: {
      merge: 'name',
      debotify: true,
      exclude: [],
      include: [],
    },
    internalDomain: [],
    internalDomains: [],
    ga: false,
    hubspot: false,
    jobs: false,
    lastUpdated: {
      text: 'Updated',
      formatOptions: {
        dateStyle: 'timeago',
      },
    },
    layouts: {},
    nav: [],
    robots: {
      allowAll: true,
    },
    sidebar: {},
    sitemap: false,
    sponsors: false,
  },
  vite: {
    resolve: {alias: []},
    plugins: [],
  },
};
