name: Run Tests

on:
  pull_request:

jobs:
  node-build-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
        node-version:
          - '20'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache version builds
        uses: actions/cache@v4
        with:
          key: lando-mvb-docs
          path: docs/.vitepress/cache/@lando/mvb
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile

      # Run tests
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Test multiversion build
        run: npx mvb docs
      - name: Test build
        run: npm run build

  bun-build-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache version builds
        uses: actions/cache@v4
        with:
          key: lando-mvb-docs
          path: docs/.vitepress/cache/@lando/mvb
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .bun-version
      - name: Install dependencies
        run: bun install

      # Run tests
      - name: Run linter
        run: bun run lint
      - name: Run tests
        run: bun run test
      - name: Test multiversion build
        run: bun run ./bin/mvb.js docs
      - name: Test build
        run: bun run build
