name: Run Tests

on:
  pull_request:

jobs:
  build-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-24.04
        node-version:
          - '18'
    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cache version builds
        uses: actions/cache@v4
        with:
          key: lando-mvb-docs
          path: docs/.vitepress/cache/@lando/mvb
          save-always: true
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm clean-install --prefer-offline --frozen-lockfile

      # Run tests
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Test build
        run: npm run build
      - name: Test multiversion build
        run: npx mvb docs --no-cache
