name: Publish to NPM and auto deploy to dependents

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - '14'
      # Install deps and cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Let's do tests rq just to make sure we dont push something that is fundamentally broken
      - name: Lint code
        run: yarn lint
      - name: Run unit tests
        run: yarn test

      # Deploy to NPM
      - name: Deploy stable releases
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_DEPLOY_TOKEN}}

  auto-deploy:
    runs-on: ${{ matrix.os }}
    needs: deploy
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - '14'
        auto-deploy-repos:
          - lando/acquia
          - lando/apache
          - lando/backdrop
          - lando/dotnet
          - lando/drupal
          - lando/elasticsearch
          - lando/go
          - lando/joomla
          - lando/lagoon
          - lando/lamp
          - lando/laravel
          - lando/lemp
          - lando/mailhog
          - lando/mariadb
          - lando/mean
          - lando/memcached
          - lando/mongo
          - lando/mssql
          - lando/mysql
          - lando/nginx
          - lando/node
          - lando/pantheon
          - lando/php
          - lando/phpmyadmin
          - lando/platformsh
          - lando/postgres
          - lando/python
          - lando/redis
          - lando/ruby
          - lando/symfony
          - lando/tomcat
          - lando/solr
          - lando/varnish
          - lando/wordpress
    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Auto deploy to everything else
      - name: Auto deploy to ${{ matrix.auto-deploy-repos }}
        uses: lando/auto-deploy-action@v2
        with:
          slug: ${{ matrix.auto-deploy-repos }}
          token: ${{ secrets.PIROG_TOKEN }}
          pr: false
          branch: main
