name: Publish to NPM and auto deploy to dependents

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        node-version:
          - '14'
        auto-deploy-repos:
          - lando/php
    steps:
      # Install deps and cache
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: yarn
      - name: Install Yarn dependencies
        run: yarn install --prefer-offline --frozen-lockfile

      # Let's do tests rq just to make sure we dont push something that is fundamentally broken
      - name: Lint code
        run: yarn lint
      - name: Run unit tests
        run: yarn test

      # Deploy to NPM
      - name: Deploy stable releases
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_DEPLOY_TOKEN}}

      # Auto deploy to everything else
      - name: Auto deploy to ${{ matrix.auto-deploy-repos }}
        uses: lando/auto-deploy-action@v2
        with:
          slug: ${{ matrix.auto-deploy-repos }}
          token: ${{ secrets.PIROG_TOKEN }}
          pr: false
          branch: main

